version: '3.3'
services:
  db:
    # image: mysql:5.7
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: 'exam0144'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'exam0144'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'vE7NmyyTsPtlayBu'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'vE7NmyyTsPtlayBu'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./persist_db:/var/lib/mysql
  php-apache-environment:
    container_name: php-apache
    build: ./php
    depends_on: 
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 80:80 # change port in local if needed from 80:80 to something:80
    expose:
      # Opens port 3306 on the container
      - '80'